version: '3'
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "base_dev"
      POSTGRES_USER: "dev_user"
      POSTGRES_PASSWORD: "123test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgresql.initdb.d:/docker-entrypoint-initdb.d
      - ./postgresql.data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d base_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  backend:
    image: busybox:latest
    volumes:
      - ./dst:/dst
    working_dir: /dst
    command: [sh,-c,"chmod +x ./exe && ./exe"]
    ports:
      - "80:80"
    depends_on: ["postgres"]